"""Modular prompt definitions — Stage L1, Summary.md section 16 ("modular
prompts, not one massive prompt") and section 17 (the strict system rules).

Each section is a small, focused unit: its own instruction text and its own
expected JSON response shape, matched to one of the Blueprint content types
Summary.md section 9 describes (`text` / `business_model` / `insight_cards`
/ `risk_cards`). Kept as plain Python data (not on-disk `.prompt` files,
which nothing else in this codebase loads) — one dict per section, in one
place, easy to add to without inventing a new file format/loader.
"""
from __future__ import annotations

# Summary.md section 17, adapted — every modular call shares this.
STRICT_SYSTEM_RULES = """You are the interpretation engine of a fundamental equity research system
for Indian stock markets.

You receive structured, verified company data generated by specialized
financial and sector agents. Your job is to interpret this data and write
concise, professional fundamental-research prose — never to fetch, invent,
or estimate anything not present in the supplied JSON.

STRICT RULES:
1. Do not fetch external information — use only the supplied JSON.
2. Never invent a number. Every figure you mention must appear in the supplied data.
3. Never estimate a missing value — if data is insufficient, say so explicitly instead.
4. Preserve units and reporting periods exactly as given.
5. Clearly distinguish historical/reported results from analyst estimates or targets.
6. Clearly distinguish facts (directly supplied) from interpretation (your synthesis of them).
7. Do not generate investment conclusions unsupported by the supplied data.
8. Keep prose tight and professional — no filler, no generic investment-commentary clichés.
9. Return ONLY the JSON object requested, matching the schema exactly."""

# id -> {title, content_type, instruction, schema_hint}
# content_type matches the renderer's dispatch key (Stage L3).
SECTIONS: dict[str, dict] = {
    "company_snapshot": {
        "title": "Company Snapshot",
        "content_type": "text",
        "instruction": (
            "Write a 2-3 sentence snapshot of this company: what sector/industry it's in, "
            "its approximate scale (market cap, current price if given), and one distinguishing "
            "fact from the business description if one is present. If the business description is "
            "empty, say the snapshot is limited to classification and market data."
        ),
        "schema_hint": '{"content": "..."}',
    },
    "business_model": {
        "title": "Business Model",
        "content_type": "business_model",
        "instruction": (
            "Explain what this company actually does and how it makes money, using ONLY the "
            "`business.about`/`business.key_points` text and sector classification supplied — this "
            "text is unstructured company-provided prose (`business.structured` is false), not "
            "verified line-item data, so treat it as descriptive context, not a source of numbers. "
            "If `operations`/`orders` are marked not_available, do not describe capacity, order book, "
            "or production figures — explicitly note that operational detail isn't available yet "
            "instead of guessing. Extract 2-4 key_points as short bullet strings if the prose supports them."
        ),
        "schema_hint": '{"content": "...", "key_points": ["...", "..."]}',
    },
    "growth_drivers": {
        "title": "Growth Drivers",
        "content_type": "insight_cards",
        "instruction": (
            "From the sector key_metrics, forward estimates, and catalysts supplied, identify up to "
            "4 distinct growth drivers or headwinds — look for relationships between metrics rather "
            "than restating each number alone (e.g. revenue growth trend + margin trend together, not "
            "separately). Each item needs a short title and a 1-2 sentence explanation grounded in the "
            "supplied figures. If the data doesn't support a real growth-driver narrative, return fewer "
            "items rather than padding with generic statements."
        ),
        "schema_hint": '{"items": [{"title": "...", "description": "..."}]}',
    },
    "financial_interpretation": {
        "title": "Financial Performance",
        "content_type": "text",
        "instruction": (
            "Interpret the supplied ratios and sector key_metrics: revenue/earnings growth trend and "
            "consistency, margin trajectory (expansion/compression and why if inferable), and capital "
            "efficiency (ROE/ROCE/ROA as applicable). 2-4 sentences. Do not restate every number — "
            "synthesize what the combination means."
        ),
        "schema_hint": '{"content": "..."}',
    },
    "balance_sheet_interpretation": {
        "title": "Balance Sheet",
        "content_type": "text",
        "instruction": (
            "Interpret leverage (debt/equity, interest coverage, current ratio) and, if shareholding "
            "data is present, promoter holding trend and pledge %. 2-3 sentences. `promoter_pct` and "
            "`pledge_pct` are two SEPARATE fields in the supplied data — never substitute one for the "
            "other. Only mention pledge % if `pledge_pct` itself is a non-null, non-zero number for "
            "that period; if `pledge_pct` is null or 0, explicitly say no pledge is on record, rather "
            "than citing `promoter_pct` as if it were the pledge figure."
        ),
        "schema_hint": '{"content": "..."}',
    },
    "cashflow_interpretation": {
        "title": "Cash Flow Quality",
        "content_type": "text",
        "instruction": (
            "Interpret cash-flow quality from the supplied FCF/CFO ratios — whether earnings are "
            "converting to cash, not the raw cash-flow statement line items. 2-3 sentences."
        ),
        "schema_hint": '{"content": "..."}',
    },
    "valuation_interpretation": {
        "title": "Valuation",
        "content_type": "text",
        "instruction": (
            "Interpret current valuation multiples against any analyst consensus targets supplied "
            "(each from a distinct named source — never average multiple sources into one figure, "
            "attribute each target to its source by name). 2-3 sentences."
        ),
        "schema_hint": '{"content": "..."}',
    },
    "risk_analysis": {
        "title": "Key Risks",
        "content_type": "risk_cards",
        "instruction": (
            "From the supplied risks, governance_events, and triggered sector red flags, produce up "
            "to 4 distinct risk cards. Each needs a severity (HIGH/MEDIUM/LOW, inherited from the "
            "supplied data — do not invent a severity not present in the source), a short title, and "
            "a 1-2 sentence description grounded in the supplied evidence."
        ),
        "schema_hint": '{"items": [{"severity": "HIGH|MEDIUM|LOW", "title": "...", "description": "..."}]}',
    },
    "sector_analysis": {
        "title": "Sector Positioning",
        "content_type": "text",
        "instruction": (
            "Given the sector's key_metrics and their status (EXCELLENT/GOOD/FAIR/POOR etc.), write "
            "2-3 sentences on how this company is positioned within its own sector framework — which "
            "areas stand out as strong or weak, using the sector-specific metric labels supplied."
        ),
        "schema_hint": '{"content": "..."}',
    },
    # ── Deep Research System (Stage R3, 2026-09-14) — same
    # STRICT_SYSTEM_RULES, same llama_interpreter.py/blueprint_validator.py
    # pipeline, fed by the real segment (R1) and news (R2) data those
    # stages ingested. No new plumbing needed: `business.segments` and
    # `news` already flow through master_object.py into every section via
    # the same numeric-grounding validator every other section here uses.
    "segment_performance": {
        "title": "Business Segment Performance",
        "content_type": "insight_cards",
        "instruction": (
            "For EACH segment supplied in `segments`, write one card: title = the segment's exact "
            "name, description = 1-2 sentences citing its `latest_revenue`, `yoy_growth_pct` (state "
            "whether it grew or declined), and `revenue_mix_pct` if not null (its share of total "
            "revenue). If `revenue_mix_pct` is null, that segment's latest figure is from an older "
            "period than the company's current reporting period — say so explicitly rather than "
            "treating it as current. Do not compute or restate any percentage yourself beyond what's "
            "supplied — use the given `yoy_growth_pct`/`revenue_mix_pct` values as-is. One card per "
            "segment, in the order supplied."
        ),
        "schema_hint": '{"items": [{"title": "...", "description": "..."}]}',
    },
    "recent_developments": {
        "title": "Recent Developments",
        "content_type": "text",
        "instruction": (
            "Summarize what recent news coverage (`recent_news`, each with headline/provider/date) has "
            "been focused on — identify the 1-2 recurring themes across the headlines (e.g. a specific "
            "corporate event, a results season, an analyst call) rather than listing every headline. "
            "You only have headlines, not full article text — characterize what topics are being "
            "covered and by whom, do not infer specifics (numbers, causes, outcomes) beyond what a "
            "headline itself states. If recent_news is sparse or unfocused, say coverage has been "
            "routine/mixed rather than forcing a narrative. 2-3 sentences."
        ),
        "schema_hint": '{"content": "..."}',
    },
    "final_conclusion": {
        "title": "What Matters Most",
        "content_type": "text",
        "instruction": (
            "In 2-3 sentences, state what an investor should actually pay attention to about this "
            "company given the scores, valuation, top risks and top catalysts supplied — prioritize, "
            "don't summarize everything again. This is a synthesis of what's already been established "
            "elsewhere, not a new rating or recommendation."
        ),
        "schema_hint": '{"content": "..."}',
    },

    # ── P&L Analysis System (Stage P2) — same STRICT_SYSTEM_RULES, same
    # llama_interpreter.py/blueprint_validator.py pipeline, no new plumbing.
    "pnl_sales_growth": {
        "title": "Sales Growth",
        "content_type": "text",
        "instruction": (
            "Interpret the supplied 10/7/5/3-year sales CAGR windows, TTM growth, recent YoY figures, "
            "and long_vs_short_trend classification (IMPROVING/MODERATING/STABLE/VOLATILE). State "
            "whether growth is accelerating or decelerating relative to the company's own longer-term "
            "history, and reference the consistency stats (negative-growth years, volatility) if they "
            "materially qualify the growth story. 2-3 sentences."
        ),
        "schema_hint": '{"content": "..."}',
    },
    "pnl_profit_growth": {
        "title": "Profit Growth",
        "content_type": "text",
        "instruction": (
            "The supplied `profit_vs_sales_direction_5y` field already tells you whether 5-year profit "
            "CAGR is FASTER, SLOWER, or ROUGHLY_IN_LINE with 5-year sales CAGR — do not compare the two "
            "numbers yourself and do not contradict this field. If FASTER, say earnings conversion/"
            "operating leverage improved (only use the term 'operating leverage' if margins data "
            "elsewhere supports it); if SLOWER, say revenue growth isn't translating proportionately "
            "into profit; if ROUGHLY_IN_LINE, say profit has tracked sales. 2-3 sentences."
        ),
        "schema_hint": '{"content": "..."}',
    },
    "pnl_margin_analysis": {
        "title": "Margin Analysis",
        "content_type": "text",
        "instruction": (
            "Interpret the supplied OPM, PBT margin and NPM: current value vs each margin's own 10Y/5Y "
            "average, peak/trough, and trend classification. State whether margins are expanding, "
            "contracting, or stable relative to the company's own history — do not state a cause unless "
            "the supplied data supports one. 2-3 sentences."
        ),
        "schema_hint": '{"content": "..."}',
    },
    "pnl_earnings_quality": {
        "title": "Earnings Quality",
        "content_type": "text",
        "instruction": (
            "Assess earnings quality from the supplied interest coverage, other-income dependency ratio, "
            "and depreciation trend. The `flagged`/`tier` fields are the ONLY basis for calling something "
            "a concern — they are already sector-aware (a bank's numbers here mean something structurally "
            "different from an industrial company's). If `other_income_dependency.flagged` is false, do "
            "NOT describe that ratio as elevated, a concern, or a vulnerability — state it neutrally or "
            "omit it entirely; only call it out if `flagged` is true. Same rule for interest coverage's "
            "`tier`: only WEAK or NEGATIVE_UNSAFE is a concern, STRONG/ADEQUATE is not, and a null tier "
            "(sector-gated, e.g. a bank) means don't discuss interest burden at all. Mention any supplied "
            "inflection points if material. 2-3 sentences."
        ),
        "schema_hint": '{"content": "..."}',
    },
    "pnl_eps_analysis": {
        "title": "EPS Analysis",
        "content_type": "text",
        "instruction": (
            "The supplied `eps_vs_profit_direction_5y` field already tells you whether 5-year EPS CAGR "
            "is FASTER, SLOWER, or ROUGHLY_IN_LINE with 5-year Net Profit CAGR — do not compare the two "
            "numbers yourself and do not contradict this field. If SLOWER, this implies share-count "
            "dilution over the period; if FASTER, buybacks or a shrinking share count; if "
            "ROUGHLY_IN_LINE, say EPS growth has tracked profit growth. 1-2 sentences."
        ),
        "schema_hint": '{"content": "..."}',
    },
    "pnl_conclusion": {
        "title": "P&L Conclusion",
        "content_type": "text",
        "instruction": (
            "Synthesize the supplied P&L quality score, red flags, positive signals, ROE trend, and "
            "Stock Price CAGR into a 2-3 sentence conclusion — what does the P&L history as a whole say "
            "about this company, and what's the single most important thing to monitor going forward. "
            "This is a synthesis of the P&L-specific findings only, not a restatement of the separate "
            "overall investment conclusion elsewhere in this report."
        ),
        "schema_hint": '{"content": "..."}',
    },

    # ── P&L Analysis Engine ("P&L Intelligence") — a separate, newer,
    # additive module (app/calculations/pl_intelligence/) alongside the
    # 6 pnl_* sections above. Prefixed "pl_" (not "pnl_") specifically so
    # old vs. new P&L narrative stays visually distinct in this file, even
    # though both share the exact same STRICT_SYSTEM_RULES/
    # llama_interpreter.py/blueprint_validator.py pipeline — no new plumbing.
    "pl_peer_positioning": {
        "title": "Peer Positioning",
        "content_type": "text",
        "instruction": (
            "You are explaining PRE-COMPUTED numbers, never calculating or restating a different number "
            "than given. Interpret the supplied EBITDA-margin and PAT-margin peer percentiles (company "
            "value vs. peer median/max/percentile) — state where this company sits relative to its "
            "direct sector/industry peers. If `peer_count` is 0 or percentiles are null, say peer "
            "comparison isn't available for this company rather than guessing. 2-3 sentences."
        ),
        "schema_hint": '{"content": "..."}',
    },
    "pl_standalone_consolidated": {
        "title": "Standalone vs Consolidated",
        "content_type": "text",
        "instruction": (
            "You are explaining PRE-COMPUTED numbers, never calculating or restating a different number "
            "than given. Interpret the supplied CSR (Consolidated Structural Ratio) and its band "
            "(PRIMARILY_PARENT_DOMESTIC / MATERIAL_SUBSIDIARY_CONTRIBUTION / SIGNIFICANT_GROUP_CONTRIBUTION "
            "/ CONSOLIDATED_STRUCTURE_DOMINATES) — state what this implies about how much of the "
            "consolidated business the standalone (parent) entity represents. If `sotp_required` is "
            "true, say the consolidated score should be interpreted with a sum-of-the-parts view given "
            "the company's multiple material business segments; do not describe a segment-level PROFIT "
            "breakdown, since only segment revenue is available. If CSR is null, say the comparison isn't "
            "available (data not yet ingested for both statement types) rather than guessing. 2-3 sentences."
        ),
        "schema_hint": '{"content": "..."}',
    },
    "pl_margin_headroom": {
        "title": "Margin Headroom",
        "content_type": "text",
        "instruction": (
            "You are explaining PRE-COMPUTED numbers, never calculating or restating a different number "
            "than given. Interpret the supplied margin headroom (gap to the peer group's peak margin) "
            "and its classification, combined with the `interpretation` field (STRONG_EXPANSION_CANDIDATE "
            "/ POTENTIAL_EFFICIENCY_TURNAROUND / GROWTH_LED_COMPOUNDER / MATURE_STAGNANT_CANDIDATE). If "
            "`management_commentary` (retrieved concall excerpts) is supplied and relevant to margin "
            "trajectory, you may reference it briefly as management's own stated view — attribute it "
            "explicitly as management commentary, not as your own conclusion. If headroom is null, say "
            "it isn't available rather than guessing. 2-3 sentences."
        ),
        "schema_hint": '{"content": "..."}',
    },
    "pl_doubling_velocity": {
        "title": "Revenue & Profit Doubling Velocity",
        "content_type": "text",
        "instruction": (
            "You are explaining PRE-COMPUTED numbers, never calculating or restating a different number "
            "than given. Interpret the supplied revenue and PAT doubling-velocity figures (years, "
            "method — EMPIRICAL meaning an actual historical doubling, or CAGR_THEORETICAL meaning a "
            "trend-based estimate — and speed classification). The supplied `velocity_comparison` field "
            "already tells you whether PAT is doubling PAT_FASTER, PAT_SLOWER, or ROUGHLY_SAME as "
            "revenue — do NOT compare the two doubling-year numbers yourself, and do not contradict this "
            "field. PAT_FASTER (fewer years for PAT to double than revenue) means margin expansion / "
            "operating leverage; PAT_SLOWER means margin compression or cost pressure; ROUGHLY_SAME means "
            "stable economics. Do not invent a cause beyond what the supplied operating-leverage "
            "diagnostic (if present) supports. 2-3 sentences."
        ),
        "schema_hint": '{"content": "..."}',
    },
    "pl_earnings_quality_v2": {
        "title": "Earnings Quality (P&L Intelligence)",
        "content_type": "text",
        "instruction": (
            "You are explaining PRE-COMPUTED numbers, never calculating or restating a different number "
            "than given. Interpret the supplied EQI (Earnings Quality Index = core operating revenue / "
            "total income) and its classification (HIGH_QUALITY / MODERATE_QUALITY / "
            "LOW_QUALITY_NON_CORE_DEPENDENT). A LOW_QUALITY classification means a material share of "
            "total income comes from non-operating other income (dividends, interest, investment gains, "
            "etc.), not from the core business — state this plainly if it applies. The detailed dividend/"
            "interest/capital-gains breakdown is NOT available (Screener reports Other Income as one "
            "aggregate line) — do not invent a sub-breakdown; only the aggregate other-income-to-PAT and "
            "other-income-to-EBITDA ratios are available if supplied. If `management_commentary` "
            "(retrieved concall excerpts) is supplied and relevant, you may reference it briefly, "
            "attributed explicitly as management's own words. 2-3 sentences."
        ),
        "schema_hint": '{"content": "..."}',
    },

    # ── Balance Sheet Analysis Engine — a separate, additive module
    # (app/calculations/balance_sheet_intelligence/), prefixed "bs_" for the
    # same reason "pl_" is distinct from "pnl_" above: its own visually
    # distinct namespace in this file despite sharing the exact same
    # STRICT_SYSTEM_RULES/pipeline, no new plumbing.
    "bs_structure_and_liquidity": {
        "title": "Balance Sheet Structure & Liquidity",
        "content_type": "text",
        "instruction": (
            "You are explaining PRE-COMPUTED numbers, never calculating or restating a different number "
            "than given. Interpret the supplied balance sheet integrity status, the Sources-vs-Applications "
            "House (equity/debt/other liabilities funding fixed assets/CWIP/investments/other assets), and "
            "the common-size percentages. State what the company owns and how it's funded, in plain terms. "
            "If `balance_sheet_integrity.status` is not VALID, say the balance sheet failed validation for "
            "this period and do not interpret further. The `house`'s Debt row is a SINGLE undifferentiated "
            "figure (no short-term/long-term split exists in this app's data) — never describe it as "
            "long-term or short-term debt specifically. 2-3 sentences."
        ),
        "schema_hint": '{"content": "..."}',
    },
    "bs_working_capital": {
        "title": "Working Capital & Cash Conversion Cycle",
        "content_type": "text",
        "instruction": (
            "You are explaining PRE-COMPUTED numbers, never calculating or restating a different number "
            "than given. Interpret the supplied DSO/inventory-days/DPO/CCC figures and their trend. These "
            "use a CLOSING-BALANCE-over-TOTAL-REVENUE methodology (not average balances or credit sales) — "
            "if you mention the methodology, describe it that way, never as the more precise average-"
            "balance/credit-sales formula. A `latest_cross_check` block may show Screener's own independently-"
            "computed figures alongside — if the two diverge materially, note both values rather than "
            "picking one. If the working capital data is empty (e.g. a bank/NBFC, where this isn't "
            "applicable), say so rather than guessing. 2-3 sentences."
        ),
        "schema_hint": '{"content": "..."}',
    },
    "bs_leverage_and_roce": {
        "title": "Leverage & Capital Efficiency",
        "content_type": "text",
        "instruction": (
            "You are explaining PRE-COMPUTED numbers, never calculating or restating a different number "
            "than given. Interpret the supplied Debt/Equity, Liabilities/Equity (these are two DIFFERENT "
            "ratios — never conflate them), Net Debt, and ROCE (with its DuPont decomposition into EBIT "
            "margin x Capital Employed Turnover — `capital_employed_methodology` states the exact formula "
            "used, Total Assets minus Current Liabilities). A `roce_cross_check` may show up to three "
            "independently-computed ROCE figures from different methodologies/sources — if they diverge "
            "materially, note that different methodologies give different results rather than treating one "
            "as definitively correct. `net_debt_source`/`capital_employed_source` are internal data-lineage "
            "tags (e.g. \"YFINANCE_CASH\") — never quote these tag strings verbatim in your prose; if you "
            "need to mention where a figure came from, describe it in plain English instead (e.g. \"using "
            "the company's reported cash balance\"). 2-3 sentences."
        ),
        "schema_hint": '{"content": "..."}',
    },
    "bs_archetype_and_risk": {
        "title": "Balance Sheet Archetype & Risk Flags",
        "content_type": "text",
        "instruction": (
            "You are explaining PRE-COMPUTED numbers, never calculating or restating a different number "
            "than given. Interpret the supplied archetype classification (STRONG / WEAK / MIDDLE / "
            "TRANSFORMING / NOT_APPLICABLE for a financial institution) and its evidence list, plus only "
            "the risk flags with status TRIGGERED (ignore NOT_TRIGGERED and SOURCE_REQUIRED flags — those "
            "are not relevant to this narrative). State the classification and why, per the evidence "
            "given — never invent an archetype reason beyond the supplied evidence list. If no flags are "
            "TRIGGERED, say the balance sheet shows no flagged risk signals rather than inventing one. "
            "2-3 sentences."
        ),
        "schema_hint": '{"content": "..."}',
    },
    "bs_coverage_summary": {
        "title": "Balance Sheet Data Coverage",
        "content_type": "text",
        "instruction": (
            "You are explaining PRE-COMPUTED numbers, never calculating or restating a different number "
            "than given. Interpret the supplied coverage percentage and the top source gaps (ranked by "
            "priority). Explain plainly what analysis IS and ISN'T possible for this company given the "
            "data actually available — e.g. if AR/inventory/AP aging or debt maturity show as a gap, say "
            "those specific analyses aren't available rather than describing coverage only in the "
            "abstract. Do not speculate about WHY a gap exists beyond what's supplied. 2-3 sentences."
        ),
        "schema_hint": '{"content": "..."}',
    },

    # ── Cash Flow Analysis Engine — a separate, additive module
    # (app/calculations/cash_flow_intelligence/), prefixed "cf_" for its own
    # namespace, same STRICT_SYSTEM_RULES/pipeline as every section above.
    # Primary-sourced from Screener.in's undocumented "schedules" API.
    "cf_reconciliation_and_conversion": {
        "title": "Cash Flow Reconciliation & Conversion",
        "content_type": "text",
        "instruction": (
            "You are explaining PRE-COMPUTED numbers, never calculating or restating a different number "
            "than given. Interpret the supplied CFO bridge (Operating Profit -> +/- Working Capital -> "
            "- Taxes Paid -> CFO) and the CFO/Operating Profit conversion ratio with its band (<50% / "
            "50-100% / ~100% / >100%). If `cfo_bridge_check.status` is DIVERGENT, note that the bridge's "
            "own arithmetic diverges from the company's reported CFO by more than a rounding-noise "
            "tolerance (this usually means an exceptional/one-off item outside the standard schedule "
            "shape) — do not silently pick one figure as correct. State the conversion trend "
            "(IMPROVING/DETERIORATING/STABLE) alongside the level. 2-3 sentences."
        ),
        "schema_hint": '{"content": "..."}',
    },
    "cf_working_capital_and_investing": {
        "title": "Working Capital Impact & Investing Activity",
        "content_type": "text",
        "instruction": (
            "You are explaining PRE-COMPUTED numbers, never calculating or restating a different number "
            "than given. Interpret the supplied working-capital cash impact (receivables/inventory/"
            "payables — already cash-flow-impact-signed, so a negative receivables figure means "
            "receivables GREW and tied up cash) and the investing-activity breakdown (capex, asset sales, "
            "investment purchases/sales, acquisitions). If `asset_sale_dependency.triggered` is true, "
            "note that investing cash flow relies materially on selling assets/investments rather than an "
            "operating-linked investing gain — this is descriptive, not automatically negative, so frame "
            "it as a pattern to note rather than a verdict. 2-3 sentences."
        ),
        "schema_hint": '{"content": "..."}',
    },
    "cf_financing_and_fcf": {
        "title": "Financing Activity & Free Cash Flow",
        "content_type": "text",
        "instruction": (
            "You are explaining PRE-COMPUTED numbers, never calculating or restating a different number "
            "than given. Interpret the supplied financing breakdown (GROSS debt raised vs. repaid — two "
            "DIFFERENT figures, never conflate them into a single net number when both are given — "
            "interest paid, dividends paid) and the free cash flow quality classification across multiple "
            "periods (CONSISTENT_POSITIVE_FCF / VOLATILE_FCF / INTERMITTENT_FCF / PERSISTENT_NEGATIVE_FCF). "
            "`buyback_proxy_value` (when present) is Screener's closest available line to a share buyback "
            "('Redemption/Cancellation of Shares') — note it conflates buybacks with other capital-"
            "reduction events, never describe it as a clean, confirmed buyback figure. 2-3 sentences."
        ),
        "schema_hint": '{"content": "..."}',
    },
    "cf_archetype_and_risk": {
        "title": "Cash Flow Archetype & Risk Flags",
        "content_type": "text",
        "instruction": (
            "You are explaining PRE-COMPUTED numbers, never calculating or restating a different number "
            "than given. Interpret the supplied cash flow archetype classification (CASH_COMPOUNDER / "
            "CASH_HARVEST / GROWTH_REINVESTMENT / ASSET_LIQUIDATION_SUPPORTED / WORKING_CAPITAL_TRAP / "
            "DEBT_FUNDED_BUSINESS / MIXED) and its evidence list — this is an ANALYTICAL ARCHETYPE, "
            "explicitly not an investment rating, so never phrase it as a buy/sell/hold recommendation. "
            "Then cover only the risk flags and forensic patterns with status TRIGGERED (ignore "
            "NOT_TRIGGERED/OBSERVED entries — those aren't relevant to this narrative). If none are "
            "TRIGGERED, say the cash flow profile shows no flagged risk signals rather than inventing "
            "one. 2-3 sentences."
        ),
        "schema_hint": '{"content": "..."}',
    },
    "cf_coverage_summary": {
        "title": "Cash Flow Data Coverage",
        "content_type": "text",
        "instruction": (
            "You are explaining PRE-COMPUTED numbers, never calculating or restating a different number "
            "than given. Interpret the supplied coverage percentage and the top source gaps (ranked by "
            "priority). Explain plainly what analysis IS and ISN'T possible for this company given the "
            "data actually available — e.g. if FX/currency-translation adjustment or a clean buyback line "
            "show as a gap, say those specific analyses aren't available rather than describing coverage "
            "only in the abstract. Do not speculate about WHY a gap exists beyond what's supplied. "
            "2-3 sentences."
        ),
        "schema_hint": '{"content": "..."}',
    },
}
